version: '3.8'
services:
  # documentation:
    # build:
    #   context: ./documentation
    #   dockerfile: Dockerfile
    # ports:
    #   - 3002:3002
    # environment:
    #   - PORT=3002
    #   - DOCS_URL=http://0.0.0.0
    #   - DOCS_BASE_URL=/
    # volumes:
    #   - ./documentation:/app
    #   - /app/node_modules

  mock-app:
    image: ghcr.io/jballment/freshchain-test-untp-mock-app:latest
    # image: ghcr.io/jballment/fumigation-test-untp-mock-app@sha256:1bc7fc33ca9f4745c5d6d6d44580a1ffdbfe7b4fd5d6fcd565c04e435e089041
    ports:
      - 3003:80
    restart: always

  vckit-api:
# newer    image: ghcr.io/uncefact/project-vckit:sha-a21556a@sha256:f75ef2de34ce587b0d54c9a7cd8d63f9d6c9cacbce191c893537dadd588ee368
    image: ghcr.io/uncefact/project-vckit:sha-60d583b@sha256:afa777d13512628e4277566a8abf45be43bdd19cdc8cbcc5383ffc00cc0ba912
    env_file:
      - local.env
    ports:
      - 3332:3332
    depends_on:
      - db
    restart: always

  db:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vckit
    volumes:
      - vckit-data:/var/lib/postgresql/data
    restart: always

  storage-service:
    image: ghcr.io/uncefact/project-identity-resolver:sha-40264dd@sha256:aa3edd2f142f0edabfa9c7b1e16b6a69835913cc1fc345f3e478c7801c0eb060
    ports:
      - 3334:443
    environment:
      - API_VERSION=v1
      - PROTOCOL=https
      - DOMAIN=vcs.freshchain.pyx.io
      - PORT=443
      - AVAILABLE_BUCKETS=verifiable-credentials,private-verifiable-credentials,epcis-events
      - STORAGE_TYPE=local
    volumes:
      - ./storage-data:/app/src/uploads
    restart: always

  identity-resolver-service:
    # Replace with local or deployed image
    image: ghcr.io/pyx-industries/pyx-identity-resolver:latest@sha256:71a02b8b0a2b9c7cc18d33a54060e9af4d543e34bdd6a47c3b3cf4dcadb1711e
    ports:
      - '3000:3000'
    environment:
      - MINIO_ENDPOINT=identity-resolver-service-object-store
      - MINIO_PORT=9000
      - MINIO_USE_SSL=false
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET_NAME=idr-bucket-1
      - MINIO_PATH_STYLE=true
      - IDENTIFIER_PATH=identifiers
      - API_KEY=test123
      - APP_ENDPOINT=https://idr.freshchain.pyx.io
      - APP_NAME=IDR-1
      - RESOLVER_DOMAIN=https://idr.freshchain.pyx.io
      - LINK_TYPE_VOC_DOMAIN=https://idr.freshchain.pyx.io/voc
      - PORT=3000
    depends_on:
      - identity-resolver-service-object-store
    restart: always

  identity-resolver-service-object-store:
    image: quay.io/minio/minio:RELEASE.2024-08-17T01-24-54Z-cpuv1
    command: server /data --console-address ":9090"
    ports:
      - '9000:9000'
      - '9090:9090'
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - ./minio_data/identity-resolver-service-object-store:/data
    restart: always

  mock-global-gs1-resolver:
    # Replace with local or deployed image
    image: ghcr.io/pyx-industries/pyx-identity-resolver:latest@sha256:71a02b8b0a2b9c7cc18d33a54060e9af4d543e34bdd6a47c3b3cf4dcadb1711e
    ports:
      - '3001:3001'
    environment:
      - MINIO_ENDPOINT=mock-global-gs1-resolver-object-store
      - MINIO_PORT=9000
      - MINIO_USE_SSL=false
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET_NAME=idr-bucket-2
      - MINIO_PATH_STYLE=true
      - IDENTIFIER_PATH=identifiers
      - API_KEY=test456
      - APP_ENDPOINT=https:/mock-gs1-idr.freshchain.pyx.io
      - APP_NAME=IDR-2
      - RESOLVER_DOMAIN=https:/mock-gs1-idr.freshchain.pyx.io
      - LINK_TYPE_VOC_DOMAIN=https:/mock-gs1-idr.freshchain.pyx.io/voc
      - PORT=3001
    depends_on:
      - mock-global-gs1-resolver-object-store
    restart: always

  mock-global-gs1-resolver-object-store:
    image: quay.io/minio/minio:RELEASE.2024-08-17T01-24-54Z-cpuv1
    command: server /data --console-address ":9091"
    ports:
      - '9001:9000'
      - '9091:9090'
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - ./minio_data/mock-global-gs1-resolver-object-store:/data
    restart: always

  # seeding-data:
  #   image: alpine:3.20.3
  #   environment:
  #     # IDR service environment variables
  #     - IDR_SERVICE_HOST=localhost
  #     - IDR_SERVICE_PORT=3000
  #     - IDR_SERVICE_API_KEY=test123

  #     # Mock GS1 service environment variables
  #     - IDR_SERVICE_DOMAIN=http://localhost:3000
  #     - MOCK_GS1_SERVICE_HOST=localhost
  #     - MOCK_GS1_SERVICE_PORT=3001
  #     - MOCK_GS1_SERVICE_API_KEY=test456
  #   command:
  #     - /bin/sh
  #     - -c
  #     - |
  #       if [ "$SEEDING" = "true" ]; then
  #         apk add curl jq && \
  #         ./seeding/idr-data.sh
  #         ./seeding/mock-gs1-data.sh
  #       fi
  #   volumes:
  #     - ./seeding:/seeding
  #   depends_on:
  #     - identity-resolver-service
  #     - mock-global-gs1-resolver

volumes:
  vckit-data:
